### ISSUE TITLE
ssl error on ping

### ISSUE THREAD

**Issue by mrcasablr** [Urigo/graphql-cli#122]
[mrcasablr@localhost tools]$ graphql ping
Sending { __typename } query to https://api.example.com:2443/graphql
✖ 
request to https://api.example.com:2443/graphql failed, reason: write EPROTO 140549953075008:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:s23_clnt.c:800:

**Comment by ardatan** [comment]
Currently we have new structure for GraphQL CLI and in the new alpha version 4.0.0-alpha.0 . We don't have `ping` command in our new alpha version. But if you have any suggestion to have it instead of having a playground, please feel free to open a new issue or create a PR. Also feel free to contact us using our Discord channnel.

**Comment by Urigo** [comment]
We've just released a new alpha versions channel for GraphQL CLI - `4.0.0-alpha.XXX`!

It was a complete rewrite of the library.
We currently haven't migrated the `ping` command in our new alpha versions because we want to first hear about the use cases you are using that command for.

Could you please elaborate on that use case here, on a new issue or on our [Discord channnel](https://discord.gg/xud7bH)?

Thank you!

**Comment by Urigo** [comment]
I've posted the wrong Discord link, this is the correct one: https://discord.gg/xud7bH9
