### ISSUE TITLE
Graphql prepare does not generate new schema when service is unchanged

### ISSUE THREAD

**Issue by LawJolla** [Urigo/graphql-cli#297]
This issue is an edge case and may not be worth considering, but food for thought.  Here was my flow using Prisma 1.8.

1.  Do not commit `prisma.graphql`  (we can debate if that's a good choice.. probably not)
2.  Change an enum
3.  `prisma deploy`
4.  Go to another instance of the project (e.g. a computer at home vs work)
5.  `prisma deploy`
6.  No change to `prisma.graphql` (schema not updated with new enum)

In the following screencast, it appears to regenerate the schema.
https://cl.ly/2E2m2D111m2N

But the schema does not regenerate when the service is up to date.  This led to a good bit of confusion why the second computer couldn't get the updated schema.  

For my situation, simply committing the schema would solve this.  But I could see this still being a problem in naive teams where a service updates (on shared dev) without a commit.  I think a message saying that `graphql prepare` did not update anything would solve it.

As always, thanks for everyone's hard work and making our/my life so much better!

**Comment by ardatan** [comment]
Currently we have new structure for GraphQL CLI and in the new alpha version `4.0.0-alpha.0` 
Checkout new instructions and we will be happy to hear your feedback. 
Feel free to contact us using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
We've just released a new version and an alpha release channel for GraphQL CLI - `4.0.0-alpha.XXX`!

In order to receive schemas the new [new GraphQL Config](https://medium.com/the-guild/graphql-config-708dd0e5d15f) which let's you specify multiple schemas from any source possible.

I want to ask the people on this issue, in that case, why would you need the `prepare` command?
Are we missing anything and should we add this command back?

Checkout new instructions and the [migration guide](https://github.com/urigo/graphql-cli#migration-from-3xx-to-4xx) and we will be happy to hear your feedback during the alpha period!

Feel free to contact us by opening an issue or using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
I've posted the wrong Discord link, this is the correct one: https://discord.gg/xud7bH9
