### ISSUE TITLE
graphql query requires named query / mutation

### ISSUE THREAD

**Issue by tianhuil** [Urigo/graphql-cli#381]
**Describe the bug**
Using the `graphql query` doesn't work if the query / mutation are unnamed.

**Error** Using the `graphql query` doesn't work if the query / mutation are unnamed:
```
$ graphql -p project query query.graphql
✖
Cannot read property 'value' of undefined
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
where `query.graphql` is
```
query {
  users {
    id
  }
}
```

**To work properly**: To get a query to work, you need to name the query / operation and pass the operation name in
```
$ graphql -p project query query.graphql -o User
{
  "data": {
    "user1": {
      "id": "cjq3eeugq000q0b10nppy1926"
    },
    "user2": {
      "id": "cjq3eeumq00100b10blf05m3i"
    }
  }
}
Done in 2.22s.
```
where `query.graphql` is
```
query User {
  users {
    id
  }
}
```

**Expected behavior**
I would expect a more descriptive error message than `Cannot read property 'value' of undefined`, perhaps `"Can only use named query with graphql-cli"`.

**Context:** similar to:
- https://github.com/graphql-cli/graphql-cli/issues/246

**Comment by ardatan** [comment]
Currently we have new structure for GraphQL CLI and in the new alpha version 4.0.0-alpha.0 . We don't have `query` command in our new alpha version. But if you have any suggestion to have it instead of having a playground, please feel free to open a new issue or create a PR. Also feel free to contact us using our Discord channnel.

**Comment by Urigo** [comment]
We've just released a new alpha versions channel for GraphQL CLI - `4.0.0-alpha.XXX`!

It was a complete rewrite of the library.
We currently haven't migrated the `query` command in our new alpha versions because we want to first hear about the use cases you are using that command for.

Could you please elaborate on that use case here, on a new issue or on our [Discord channnel](https://discord.gg/xud7bH)?

Thank you!

**Comment by Urigo** [comment]
I've posted the wrong Discord link, this is the correct one: https://discord.gg/xud7bH9
